services:
  backend:
    build: ./backend
    container_name: phonebook-backend
    restart: unless-stopped
    ports:
      - "8001:8000"      # Хост:8001 -> Контейнер:8000
    env_file:
      - ./backend/.env
    networks:
      - phonebook-network

  frontend:
    build: ./frontend
    container_name: phonebook-frontend
    restart: unless-stopped
    ports:
      - "8989:8989"      # Хост:8989 -> Контейнер:8989
    depends_on:
      - backend
    networks:
      - phonebook-network

networks:
  phonebook-network:
    driver: bridge